import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';class TimerScreen extends StatelessWidget {const TimerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgTimeManagementBro, height: 267.adaptSize, width: 267.adaptSize), SizedBox(height: 19.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildTimerMinutes(context, minutesText: "Hours", oneText: "00"), CustomImageView(imagePath: ImageConstant.imgClose, height: 16.v, width: 6.h, margin: EdgeInsets.only(left: 10.h, top: 36.v, bottom: 22.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: _buildTimerMinutes(context, minutesText: "Minutes", oneText: "01")), CustomImageView(imagePath: ImageConstant.imgClose, height: 16.v, width: 6.h, margin: EdgeInsets.only(left: 10.h, top: 36.v, bottom: 22.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: _buildTimerMinutes(context, minutesText: "Seconds", oneText: "30"))]), SizedBox(height: 34.v), _buildWorkoutTimer(context), SizedBox(height: 89.v), _buildPause(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 38.v, bottom: 36.v)), centerTitle: true, title: AppbarSubtitle(text: "Timer"), styleType: Style.bgStyle_6); } 
/// Section Widget
Widget _buildWorkoutTimer(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Workout Timer", style: CustomTextStyles.labelLargeSemiBold_1)), SizedBox(height: 7.v), _buildWorkoutEnom(context, textLabel: "Amrap"), SizedBox(height: 8.v), _buildWorkoutEnom(context, textLabel: "Enom"), SizedBox(height: 8.v), _buildWorkoutEnom(context, textLabel: "Tabata", onTapWorkoutEnom: () {onTapTabata(context);})]); } 
/// Section Widget
Widget _buildPause(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(width: 99.h, text: "Pause", buttonStyle: CustomButtonStyles.outlineWhiteA, buttonTextStyle: CustomTextStyles.bodyMediumPrimary), CustomOutlinedButton(width: 90.h, text: "Start"), CustomOutlinedButton(width: 95.h, text: "Reset", buttonStyle: CustomButtonStyles.outlineWhiteA, buttonTextStyle: CustomTextStyles.bodyMediumPrimary)])); } 
/// Common widget
Widget _buildTimerMinutes(BuildContext context, {required String minutesText, required String oneText, }) { return Column(children: [Text(minutesText, style: CustomTextStyles.labelSmallPrimary.copyWith(color: theme.colorScheme.primary)), SizedBox(height: 2.v), Container(padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 5.v), decoration: AppDecoration.outlineGray60002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text(oneText, style: theme.textTheme.headlineLarge!.copyWith(color: appTheme.gray800))]))]); } 
/// Common widget
Widget _buildWorkoutEnom(BuildContext context, {required String textLabel, Function? onTapWorkoutEnom, }) { return GestureDetector(onTap: () {onTapWorkoutEnom!.call();}, child: Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text(textLabel, style: theme.textTheme.labelMedium!.copyWith(color: appTheme.gray800))), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v, right: 7.h))]))); } 
/// Navigates to the tabatatimerScreen when the action is triggered.
onTapTabata(BuildContext context) { Navigator.pushNamed(context, AppRoutes.tabatatimerScreen); } 
 }
