import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle_three.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_trailing_image.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';class MoreOneScreen extends StatelessWidget {const MoreOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildTealBg(context), _buildAvailableVideos(context)])))); } 
/// Section Widget
Widget _buildTealBg(BuildContext context) { return SizedBox(height: 122.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomAppBar(height: 122.v, centerTitle: true, title: Column(children: [AppbarSubtitle(text: "Library of Movements"), AppbarSubtitleThree(text: "Cardio", margin: EdgeInsets.symmetric(horizontal: 75.h))]), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgGroup5Teal40001, margin: EdgeInsets.only(left: 12.h, right: 12.h, bottom: 35.v))], styleType: Style.bgFill), Align(alignment: Alignment.topLeft, child: Container(height: 111.v, width: 70.h, margin: EdgeInsets.only(left: 7.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 38.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgVectorTeal400), fit: BoxFit.cover)), child: CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topLeft, onTap: () {onTapImgArrowDown(context);})))])); } 
/// Section Widget
Widget _buildAvailableVideos(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 24.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("Available videos", style: CustomTextStyles.labelLargeSemiBold_1))), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 2.h), child: _buildYoutubeOne(context, howToDoADeadlift: "How to Do a Deadlift by Wodstar")), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 2.h), child: _buildYoutubeOne(context, howToDoADeadlift: "How to Do a Deadlift by Wodstar")), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 2.h), child: _buildYoutubeOne(context, howToDoADeadlift: "How to Do a Deadlift by Wodstar")), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 2.h), child: _buildYoutubeOne(context, howToDoADeadlift: "How to Do a Deadlift by Wodstar")), SizedBox(height: 5.v)])); } 
/// Common widget
Widget _buildYoutubeOne(BuildContext context, {required String howToDoADeadlift, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgYoutube1, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v, bottom: 2.v), child: Text(howToDoADeadlift, style: theme.textTheme.labelMedium!.copyWith(color: appTheme.gray800))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v, right: 7.h))])); } 
/// Navigates to the communityBoardThreeScreen when the action is triggered.
onTapImgArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.communityBoardThreeScreen); } 
 }
