import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';import 'package:gaiadhiwise/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SubmitO2RingScreen extends StatelessWidget {SubmitO2RingScreen({Key? key}) : super(key: key);

TextEditingController nameController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildVectorStack(context), Container(padding: EdgeInsets.symmetric(horizontal: 44.h, vertical: 19.v), child: Column(children: [_buildTwentyThreeColumn(context), SizedBox(height: 13.v), _buildNameColumn(context), SizedBox(height: 13.v), _buildDateOfSubmissionColumn(context), SizedBox(height: 40.v), CustomOutlinedButton(text: "Upload PDF", onPressed: () {onTapUploadPDF(context);}), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildORingImage(BuildContext context) { return CustomImageView(imagePath: ImageConstant.imgImage11, height: 196.v, width: 305.h); } 
/// Section Widget
Widget _buildORingColumn(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 41.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(padding: EdgeInsets.symmetric(horizontal: 53.h, vertical: 19.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 63.h), child: Text("O2 Ring ", style: CustomTextStyles.titleMedium18)), Text("Kindly submit your O2 ring PDF File", style: CustomTextStyles.bodySmallGray60001)])), SizedBox(height: 35.v), _buildORingImage(context)]))); } 
/// Section Widget
Widget _buildVectorStack(BuildContext context) { return SizedBox(height: 403.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 26.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup56), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 56.v), CustomAppBar(height: 24.v, leadingWidth: double.maxFinite, leading: Container(height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.fromLTRB(29.h, 5.v, 350.h, 5.v), child: Stack(alignment: Alignment.centerLeft, children: [CustomImageView(imagePath: ImageConstant.imgVector, height: 2.v, width: 14.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(top: 7.v, bottom: 5.v)), CustomImageView(imagePath: ImageConstant.imgVectorWhiteA700, height: 14.v, width: 7.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(right: 7.h), onTap: () {onTapImgVector(context);})])))]))), _buildORingColumn(context)])); } 
/// Section Widget
Widget _buildTwentyThreeColumn(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("File preview", style: CustomTextStyles.bodySmallGray80012), SizedBox(height: 1.v), Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 5.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 33.v, width: 35.h, margin: EdgeInsets.only(bottom: 1.v), decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(5.h))), Padding(padding: EdgeInsets.only(left: 10.h, top: 5.v, bottom: 7.v), child: Text("No selected file", style: CustomTextStyles.bodyMediumBluegray200))]))]); } 
/// Section Widget
Widget _buildNameColumn(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Custom file name", style: CustomTextStyles.bodySmallGray80012), SizedBox(height: 2.v), CustomTextFormField(controller: nameController, textInputAction: TextInputAction.done)]); } 
/// Section Widget
Widget _buildDateOfSubmissionColumn(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Date of submission", style: CustomTextStyles.bodySmallGray80012), SizedBox(height: 2.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 8.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("01/12/2023", style: CustomTextStyles.bodyMediumGray800)), CustomImageView(imagePath: ImageConstant.imgCalendar11, height: 20.adaptSize, width: 20.adaptSize)]))]); } 

/// Navigates back to the previous screen.
onTapImgVector(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the dailyContainer1Screen when the action is triggered.
onTapUploadPDF(BuildContext context) { Navigator.pushNamed(context, AppRoutes.dailyContainer1Screen); } 
 }
