import '../more_five_screen/widgets/notetext_item_widget.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_icon_button.dart';import 'package:gaiadhiwise/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class MoreFiveScreen extends StatelessWidget {MoreFiveScreen({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildStack(context), _buildAllNotes(context)])))); } 
/// Section Widget
Widget _buildStack(BuildContext context) { return SizedBox(height: 160.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 34.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup56), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 35.v), CustomAppBar(height: 27.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 3.v)), centerTitle: true, title: AppbarSubtitle(text: "Notes"))]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(left: 24.h, top: 103.v, right: 24.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 1.v), child: CustomSearchView(controller: searchController, hintText: "Search note...", contentPadding: EdgeInsets.only(left: 10.h, top: 9.v, bottom: 9.v)))), Padding(padding: EdgeInsets.only(left: 19.h, top: 1.v), child: CustomIconButton(height: 36.v, width: 38.h, onTap: () {onTapBtnFacebook(context);}, child: CustomImageView(imagePath: ImageConstant.imgDownloadWhiteA700)))])))])); } 
/// Section Widget
Widget _buildAllNotes(BuildContext context) { return Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 34.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("All notes", style: theme.textTheme.labelLarge), SizedBox(height: 5.v), Expanded(child: Padding(padding: EdgeInsets.only(right: 3.h), child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 10.v);}, itemCount: 2, itemBuilder: (context, index) {return NotetextItemWidget(onTapNoteText: () {onTapNoteText(context);});})))])))); } 
/// Navigates to the moreScreen when the action is triggered.
onTapNoteText(BuildContext context) { Navigator.pushNamed(context, AppRoutes.moreScreen); } 
/// Navigates to the moreTwoScreen when the action is triggered.
onTapBtnFacebook(BuildContext context) { Navigator.pushNamed(context, AppRoutes.moreTwoScreen); } 
 }
