import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/presentation/community_board_six_bottomsheet/community_board_six_bottomsheet.dart';class CommunityBoardEightScreen extends StatelessWidget {const CommunityBoardEightScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), child: Column(children: [SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: Row(children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Beginner", style: CustomTextStyles.titleSmallPrimary), Text("Level", style: CustomTextStyles.bodySmall10)]), Padding(padding: EdgeInsets.only(left: 30.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("30 mins", style: CustomTextStyles.titleSmallPrimary), Text("Duration", style: CustomTextStyles.bodySmall10)])), Padding(padding: EdgeInsets.only(left: 30.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("3 sets", style: CustomTextStyles.titleSmallPrimary), Text("Sets", style: CustomTextStyles.bodySmall10)]))])), SizedBox(height: 26.v), _buildWarmUp(context), SizedBox(height: 12.v), _buildMainExercise(context)])), bottomNavigationBar: _buildCoolDown(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 38.v, bottom: 36.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitle(text: "Upper body Workout"), styleType: Style.bgStyle_5); } 
/// Section Widget
Widget _buildWarmUp(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Warm-up", style: CustomTextStyles.labelLargeSemiBold_1)), SizedBox(height: 11.v), GestureDetector(onTap: () {onTapJumpingJack(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Jumping Jack", style: theme.textTheme.labelLarge), Text("00:30", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))]))), SizedBox(height: 8.v), Container(padding: EdgeInsets.all(9.h), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Arm circles", style: theme.textTheme.labelLarge), Text("00:30", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 6.v, bottom: 7.v))])), SizedBox(height: 8.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Lateral Steps", style: theme.textTheme.labelLarge), Text("01:00", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])), SizedBox(height: 8.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Hip rotation", style: theme.textTheme.labelLarge), Text("00:30", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))]))]); } 
/// Section Widget
Widget _buildMainExercise(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Main exercise", style: CustomTextStyles.labelLargeSemiBold_1)), SizedBox(height: 13.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Push up", style: theme.textTheme.labelLarge), Text("x10", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])), SizedBox(height: 8.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Wide arm push up", style: theme.textTheme.labelLarge), Text("x10", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])), SizedBox(height: 8.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Knee push up", style: theme.textTheme.labelLarge), Text("x10", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))])), SizedBox(height: 8.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Triceps Dips", style: theme.textTheme.labelLarge), Text("x16", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))]))]); } 
/// Section Widget
Widget _buildCoolDown(BuildContext context) { return Container(margin: EdgeInsets.only(bottom: 8.v), padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Cool down", style: CustomTextStyles.labelLargeSemiBold_1), Container(margin: EdgeInsets.only(top: 13.v), padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Cross-body shoulder stretch", style: theme.textTheme.labelLarge), Text("01:00", style: CustomTextStyles.bodySmall10)]), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 6.v))]))])); } 
/// Navigates to the beginnerScreen when the action is triggered.
onTapArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.beginnerScreen); } 

/// Shows a modal bottom sheet with [CommunityBoardSixBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapJumpingJack(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>CommunityBoardSixBottomsheet(),isScrollControlled: true); } 
 }
