import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_icon_button.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';class MoreSevenScreen extends StatelessWidget {const MoreSevenScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildStack(context), _buildColumn2(context)])))); } 
/// Section Widget
Widget _buildStack(BuildContext context) { return SizedBox(height: 160.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 37.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup56), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 29.v), CustomAppBar(height: 27.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, bottom: 2.v)), centerTitle: true, title: AppbarSubtitle(text: "Weekly Meal Tracking"))]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(left: 24.h, top: 103.v, right: 24.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(height: 36.v, width: 194.h, text: "Dec 1 2023 - Dec 30 2023", margin: EdgeInsets.only(top: 1.v), rightIcon: Container(margin: EdgeInsets.only(left: 8.h), child: CustomImageView(imagePath: ImageConstant.imgCalendar11Primary, height: 18.adaptSize, width: 18.adaptSize)), buttonStyle: CustomButtonStyles.outlineWhiteA, buttonTextStyle: CustomTextStyles.bodySmallPrimary), Padding(padding: EdgeInsets.only(top: 1.v), child: CustomIconButton(height: 36.v, width: 38.h, child: CustomImageView(imagePath: ImageConstant.imgDownloadWhiteA700)))])))])); } 
/// Section Widget
Widget _buildColumn2(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 34.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Date", style: theme.textTheme.labelLarge)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(right: 3.h), child: _buildColumn(context, thursday: "2023-10-30 (Monday)", breakfast: "Breakfast", lunch: "Lunch", checkImage: ImageConstant.imgX1, dinner: "Dinner", snacks: "Snacks", onTapColumn: () {onTapMonday(context);})), SizedBox(height: 12.v), GestureDetector(onTap: () {onTapSaturday(context);}, child: Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.whiteA700, shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.gray30002, width: 1.h), borderRadius: BorderRadiusStyle.roundedBorder6), child: Container(height: 64.v, width: 340.h, padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Text("2023-10-28 (Saturday)", style: theme.textTheme.labelMedium)), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 2.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 16.v), child: _buildRow(context, breakfastText: "Breakfast", lunchText: "Lunch", dinnerText: "Dinner", snacksText: "Snacks")), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 28.h, bottom: 7.v))])))])))), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(right: 3.h), child: _buildColumn(context, thursday: "2023-10-26 (Thursday)", breakfast: "Breakfast", lunch: "Lunch", checkImage: ImageConstant.imgCheck11, dinner: "Dinner", snacks: "Snacks", onTapColumn: () {onTapColumn(context);})), SizedBox(height: 5.v)])); } 
/// Common widget
Widget _buildRow(BuildContext context, {required String breakfastText, required String lunchText, required String dinnerText, required String snacksText, }) { return Expanded(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text(breakfastText, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500)), CustomImageView(imagePath: ImageConstant.imgCheck11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text(lunchText, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500))), CustomImageView(imagePath: ImageConstant.imgCheck11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text(dinnerText, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500))), CustomImageView(imagePath: ImageConstant.imgCheck11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text(snacksText, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500))), CustomImageView(imagePath: ImageConstant.imgCheck11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h))])); } 
/// Common widget
Widget _buildColumn(BuildContext context, {required String thursday, required String breakfast, required String lunch, required String checkImage, required String dinner, required String snacks, Function? onTapColumn, }) { return GestureDetector(onTap: () {onTapColumn!.call();}, child: Container(padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(thursday, style: theme.textTheme.labelMedium!.copyWith(color: appTheme.gray800)), SizedBox(height: 9.v), Row(children: [Text(breakfast, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500)), CustomImageView(imagePath: ImageConstant.imgCheck11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text(lunch, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500))), CustomImageView(imagePath: checkImage, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text(dinner, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500))), CustomImageView(imagePath: ImageConstant.imgCheck11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text(snacks, style: CustomTextStyles.bodySmallTeal50010.copyWith(color: appTheme.teal500))), CustomImageView(imagePath: ImageConstant.imgCheck11, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(left: 4.h))])]))), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 28.h, top: 7.v, bottom: 9.v))]))); } 
/// Navigates to the moreFifteenScreen when the action is triggered.
onTapMonday(BuildContext context) { Navigator.pushNamed(context, AppRoutes.moreFifteenScreen); } 
/// Navigates to the moreThreeScreen when the action is triggered.
onTapSaturday(BuildContext context) { Navigator.pushNamed(context, AppRoutes.moreThreeScreen); } 
/// Navigates to the moreThreeScreen when the action is triggered.
onTapColumn(BuildContext context) { Navigator.pushNamed(context, AppRoutes.moreThreeScreen); } 
 }
