import '../more_thirteen_bottomsheet/widgets/da1_item_widget.dart';import '../more_thirteen_bottomsheet/widgets/userprofilesection_item_widget.dart';import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';class MoreThirteenBottomsheet extends StatelessWidget {const MoreThirteenBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return Container(width: 392.h, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 18.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.customBorderTL22), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 3.v, width: 40.h, decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(1.h))), SizedBox(height: 24.v), _buildMealTrackingSection(context), SizedBox(height: 27.v), Expanded(child: SizedBox(width: double.maxFinite, child: Padding(padding: EdgeInsets.only(right: 1.h), child: Column(children: [_buildUserProfileSection(context), SizedBox(height: 39.v), _buildEarlySnacksSection(context), SizedBox(height: 39.v), Text("Late Snacks", style: theme.textTheme.titleMedium), SizedBox(height: 17.v), CustomImageView(imagePath: ImageConstant.imgClockBlack900, height: 90.adaptSize, width: 90.adaptSize), SizedBox(height: 5.v), Text("No late snacks available", style: CustomTextStyles.labelMediumGray60002)])))), SizedBox(height: 102.v), CustomOutlinedButton(width: 90.h, text: "Close", buttonStyle: CustomButtonStyles.outlineSecondaryContainer, onPressed: () {onTapClose(context);}), SizedBox(height: 24.v)])); } 
/// Section Widget
Widget _buildMealTrackingSection(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 1.h), child: Column(children: [Text("Meal Tracking", style: CustomTextStyles.titleMediumPrimary18), Text("2023-10-28 (Saturday)", style: CustomTextStyles.bodyMediumGray60002)])); } 
/// Section Widget
Widget _buildUserProfileSection(BuildContext context) { return Expanded(child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: 3, itemBuilder: (context, index) {return UserprofilesectionItemWidget();})); } 
/// Section Widget
Widget _buildEarlySnacksSection(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("Early Snacks", style: theme.textTheme.titleMedium)), SizedBox(height: 15.v), SizedBox(height: 58.v, child: ListView.separated(padding: EdgeInsets.only(right: 142.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 14.h);}, itemCount: 3, itemBuilder: (context, index) {return Da1ItemWidget();}))]); } 
/// Navigates to the moreSevenScreen when the action is triggered.
onTapClose(BuildContext context) { Navigator.pushNamed(context, AppRoutes.moreSevenScreen); } 
 }
