import '../capture_screen/widgets/widget2_item_widget.dart';import '../capture_screen/widgets/widget3_item_widget.dart';import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';class CaptureScreen extends StatelessWidget {const CaptureScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [_buildPhotosSection(context), SizedBox(height: 24.v), _buildVideosSection(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildOpenCameraButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 38.v, bottom: 36.v)), centerTitle: true, title: AppbarSubtitle(text: "Capture"), styleType: Style.bgStyle_11); } 
/// Section Widget
Widget _buildPhotosSection(BuildContext context) { return Expanded(child: SizedBox(width: double.maxFinite, child: Padding(padding: EdgeInsets.only(right: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Photos", style: CustomTextStyles.labelLargeSemiBold_1), SizedBox(height: 7.v), Expanded(child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 81.v, crossAxisCount: 5, mainAxisSpacing: 6.h, crossAxisSpacing: 6.h), physics: BouncingScrollPhysics(), itemCount: 10, itemBuilder: (context, index) {return Widget2ItemWidget();}))])))); } 
/// Section Widget
Widget _buildVideosSection(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Videos", style: CustomTextStyles.labelLargeSemiBold_1), SizedBox(height: 7.v), GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 81.v, crossAxisCount: 5, mainAxisSpacing: 6.h, crossAxisSpacing: 6.h), physics: NeverScrollableScrollPhysics(), itemCount: 10, itemBuilder: (context, index) {return Widget3ItemWidget();})])); } 
/// Section Widget
Widget _buildOpenCameraButton(BuildContext context) { return CustomOutlinedButton(text: "Open Camera", margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 20.v), leftIcon: Container(margin: EdgeInsets.only(right: 8.h), child: CustomImageView(imagePath: ImageConstant.imgFrameWhiteA70020x20, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimaryTL61, onPressed: () {onTapOpenCameraButton(context);}); } 
/// Navigates to the captureCameraScreen when the action is triggered.
onTapOpenCameraButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.captureCameraScreen); } 
 }
