import '../more_sixteen_bottomsheet/widgets/da_item_widget.dart';import '../more_sixteen_bottomsheet/widgets/userprofilelist_item_widget.dart';import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';class MoreSixteenBottomsheet extends StatelessWidget {const MoreSixteenBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return Container(width: 392.h, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 18.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.customBorderTL22), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 3.v, width: 40.h, decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(1.h))), SizedBox(height: 24.v), Text("Meal Tracking", style: CustomTextStyles.titleMediumPrimary18), Expanded(child: SizedBox(width: double.maxFinite, child: Padding(padding: EdgeInsets.only(right: 1.h), child: Column(children: [Text("2023-10-30 (Monday)", style: CustomTextStyles.bodyMediumGray60002), SizedBox(height: 27.v), _buildMealTrackingRow(context), SizedBox(height: 31.v), _buildUserProfileList(context), SizedBox(height: 39.v), _buildEarlySnacksColumn(context), SizedBox(height: 39.v), Text("Late Snacks", style: theme.textTheme.titleMedium), SizedBox(height: 17.v), CustomImageView(imagePath: ImageConstant.imgClockBlack900, height: 90.adaptSize, width: 90.adaptSize), SizedBox(height: 5.v), Text("No late snacks available", style: CustomTextStyles.labelMediumGray60002)])))), SizedBox(height: 102.v), CustomOutlinedButton(width: 90.h, text: "Close", buttonStyle: CustomButtonStyles.outlineSecondaryContainer, onPressed: () {onTapClose(context);}), SizedBox(height: 24.v)])); } 
/// Section Widget
Widget _buildMealTrackingRow(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.img030cfc6229ff4, height: 58.adaptSize, width: 58.adaptSize, radius: BorderRadius.circular(4.h)), Padding(padding: EdgeInsets.only(left: 8.h, top: 5.v), child: _buildLunchColumn(context, lunchText: "Breakfast", tasteScoreText: "Taste Score: N/A", satietyScoreText: "Satiety Score: N/A")), Spacer(), SizedBox(height: 58.adaptSize, width: 58.adaptSize, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.img030cfc6229ff4, height: 58.adaptSize, width: 58.adaptSize, radius: BorderRadius.circular(4.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Container(height: 58.adaptSize, width: 58.adaptSize, decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(4.h))))])), Padding(padding: EdgeInsets.only(left: 8.h, top: 6.v), child: _buildLunchColumn(context, lunchText: "Lunch", tasteScoreText: "Taste Score: N/A", satietyScoreText: "Satiety Score: N/A"))]); } 
/// Section Widget
Widget _buildUserProfileList(BuildContext context) { return Expanded(child: Align(alignment: Alignment.centerLeft, child: SizedBox(height: 59.v, child: ListView.separated(padding: EdgeInsets.only(right: 203.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 1.h);}, itemCount: 1, itemBuilder: (context, index) {return UserprofilelistItemWidget();})))); } 
/// Section Widget
Widget _buildEarlySnacksColumn(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("Early Snacks", style: theme.textTheme.titleMedium)), SizedBox(height: 15.v), SizedBox(height: 58.v, child: ListView.separated(padding: EdgeInsets.only(right: 143.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 14.h);}, itemCount: 3, itemBuilder: (context, index) {return DaItemWidget();}))]); } 
/// Common widget
Widget _buildLunchColumn(BuildContext context, {required String lunchText, required String tasteScoreText, required String satietyScoreText, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(lunchText, style: theme.textTheme.titleMedium!.copyWith(color: appTheme.gray800)), RichText(text: TextSpan(children: [TextSpan(text: "Taste Score:", style: CustomTextStyles.bodySmallGray80010), TextSpan(text: " "), TextSpan(text: "N/A", style: CustomTextStyles.labelMediumBold)]), textAlign: TextAlign.left), RichText(text: TextSpan(children: [TextSpan(text: "Satiety Score:", style: CustomTextStyles.bodySmallGray80010), TextSpan(text: " "), TextSpan(text: "N/A", style: CustomTextStyles.labelMediumBold)]), textAlign: TextAlign.left)]); } 
/// Navigates to the moreSevenScreen when the action is triggered.
onTapClose(BuildContext context) { Navigator.pushNamed(context, AppRoutes.moreSevenScreen); } 
 }
