import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';class TabatatimerScreen extends StatelessWidget {const TabatatimerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Exercise Overview", style: theme.textTheme.titleMedium)), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Row(children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("32 mins", style: CustomTextStyles.titleSmallPrimary), Text("Workout Duration", style: CustomTextStyles.bodySmall10)]), Padding(padding: EdgeInsets.only(left: 30.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("10 secs", style: CustomTextStyles.titleSmallPrimary), Text("Rest Duration", style: CustomTextStyles.bodySmall10)]))])), SizedBox(height: 16.v), Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.fillWhiteA, child: Column(children: [_buildBodyweightSquats(context, bodyweightSquatsText: "Jumping Jack", timeText: "00:20"), SizedBox(height: 8.v), _buildBodyweightSquats(context, bodyweightSquatsText: "Bodyweight Squats", timeText: "00:20"), SizedBox(height: 8.v), _buildBodyweightSquats(context, bodyweightSquatsText: "High Stepping", timeText: "00:20"), SizedBox(height: 8.v), _buildBodyweightSquats(context, bodyweightSquatsText: "Push-ups", timeText: "x12"), SizedBox(height: 8.v), _buildBodyweightSquats(context, bodyweightSquatsText: "Mountain Climbers", timeText: "00:20"), SizedBox(height: 8.v), _buildBodyweightSquats(context, bodyweightSquatsText: "Burpees", timeText: "00:20"), SizedBox(height: 8.v), _buildBodyweightSquats(context, bodyweightSquatsText: "High Knees", timeText: "00:20"), SizedBox(height: 8.v), _buildBodyweightSquats(context, bodyweightSquatsText: "Jump Lunges", timeText: "00:20"), SizedBox(height: 8.v), _buildView(context)])), SizedBox(height: 2.v)])), bottomNavigationBar: _buildStartWorkout(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 38.v, bottom: 36.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitle(text: "Tabata"), styleType: Style.bgStyle_7); } 
/// Section Widget
Widget _buildView(BuildContext context) { return SizedBox(height: 30.v, width: 345.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 55.v, width: 345.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray30002, width: 1.h)))), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 10.h), child: Text("Jump Lunges", style: theme.textTheme.labelLarge)))])); } 
/// Section Widget
Widget _buildStartWorkout(BuildContext context) { return CustomOutlinedButton(text: "Start Workout", margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 50.v), buttonStyle: CustomButtonStyles.outlinePrimaryTL61); } 
/// Common widget
Widget _buildBodyweightSquats(BuildContext context, {required String bodyweightSquatsText, required String timeText, }) { return Container(width: 345.h, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 10.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(bodyweightSquatsText, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray800)), Text(timeText, style: CustomTextStyles.bodySmall10.copyWith(color: appTheme.gray60002))])); } 
/// Navigates to the timerScreen when the action is triggered.
onTapArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.timerScreen); } 
 }
