import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';class ChallengeboardPreparationScreen extends StatelessWidget {const ChallengeboardPreparationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildTealBackground(context), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Movement Instruction", style: CustomTextStyles.labelLargeSemiBold_1))), SizedBox(height: 12.v), _buildMobilityExercises(context, mobilityExercisesText: "Warm-up", howToDoADeadliftText: "How to Do a Deadlift by Wodstar"), SizedBox(height: 13.v), _buildMobilityExercises(context, mobilityExercisesText: "Mobility Exercises", howToDoADeadliftText: "How to Do a Deadlift by Wodstar"), SizedBox(height: 12.v), _buildActivationDrills(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
Widget _buildTealBackground(BuildContext context) { return SizedBox(height: 122.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.center, child: Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.teal30001, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.customBorderBL16), child: Container(height: 122.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 11.h), decoration: AppDecoration.fillTeal30001.copyWith(borderRadius: BorderRadiusStyle.customBorderBL16), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgGroup5Teal40001, height: 87.v, width: 185.h, alignment: Alignment.topRight), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 35.v), child: Text("Deadlift 1x3", style: theme.textTheme.bodyMedium))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 37.v), child: Text("Workout Preparation", style: CustomTextStyles.titleMediumWhiteA70018)))])))), Align(alignment: Alignment.topLeft, child: Container(height: 111.v, width: 70.h, margin: EdgeInsets.only(left: 7.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 38.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgVectorTeal400), fit: BoxFit.cover)), child: CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topLeft, onTap: () {onTapImgArrowDown(context);})))])); } 
/// Section Widget
Widget _buildActivationDrills(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Activation Drills", style: theme.textTheme.labelLarge)), SizedBox(height: 5.v), _buildYoutubeOne(context, howToDoADeadlift: "How to Do a Deadlift by Wodstar"), SizedBox(height: 8.v), _buildYoutubeOne(context, howToDoADeadlift: "How to Do a Deadlift by Wodstar"), SizedBox(height: 8.v), _buildYoutubeOne(context, howToDoADeadlift: "How to Do a Deadlift by Wodstar")])); } 
/// Common widget
Widget _buildMobilityExercises(BuildContext context, {required String mobilityExercisesText, required String howToDoADeadliftText, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(mobilityExercisesText, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray800)), SizedBox(height: 4.v), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgYoutube1, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v, bottom: 2.v), child: Text(howToDoADeadliftText, style: theme.textTheme.labelMedium!.copyWith(color: appTheme.gray800))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v, right: 7.h))]))])); } 
/// Common widget
Widget _buildYoutubeOne(BuildContext context, {required String howToDoADeadlift, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineGray30002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgYoutube1, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v, bottom: 2.v), child: Text(howToDoADeadlift, style: theme.textTheme.labelMedium!.copyWith(color: appTheme.gray800))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 1.v, right: 7.h))])); } 
/// Navigates to the challengeboardScreen when the action is triggered.
onTapImgArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.challengeboardScreen); } 
 }
