import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';import 'package:gaiadhiwise/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SubmitBodyCompositionThreeScreen extends StatelessWidget {SubmitBodyCompositionThreeScreen({Key? key}) : super(key: key);

TextEditingController aftermealpreviewController = TextEditingController();

TextEditingController noteController = TextEditingController();

TextEditingController dateController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: Column(children: [_buildArrowDownSection(context), SizedBox(height: 53.v), CustomImageView(imagePath: ImageConstant.imgImage11, height: 196.v, width: 305.h), SizedBox(height: 18.v), _buildBeforeMealPreviewSection(context), SizedBox(height: 18.v), _buildAfterMealPreviewSection(context), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 44.h), child: Text("Note", style: CustomTextStyles.bodySmallGray80012))), SizedBox(height: 2.v), Padding(padding: EdgeInsets.symmetric(horizontal: 44.h), child: CustomTextFormField(controller: noteController, hintText: "Enter your note here", maxLines: 5, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 10.v))), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 44.h), child: Text("Date of submission", style: CustomTextStyles.bodySmallGray80012))), SizedBox(height: 2.v), Padding(padding: EdgeInsets.symmetric(horizontal: 44.h), child: CustomTextFormField(controller: dateController, hintText: "01/12/2023", textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 10.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgCalendar11, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 40.v), contentPadding: EdgeInsets.only(left: 14.h, top: 14.v, bottom: 14.v))), SizedBox(height: 40.v), CustomOutlinedButton(text: "Submit Form", margin: EdgeInsets.symmetric(horizontal: 44.h), onPressed: () {onTapSubmitForm(context);})]))))); } 
/// Section Widget
Widget _buildArrowDownSection(BuildContext context) { return SizedBox(height: 143.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 26.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup1061), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 11.v), CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgArrowDown(context);})]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 41.h), padding: EdgeInsets.symmetric(horizontal: 38.h, vertical: 7.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 10.v), Text("CGM ", style: CustomTextStyles.titleMedium18), SizedBox(width: 232.h, child: Text("Upload CGM photos: Before meal, after meal. Optional: Include notes", maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodySmallGray60001))])))])); } 
/// Section Widget
Widget _buildBeforeMealPreviewSection(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 44.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Before meal preview", style: CustomTextStyles.bodySmallGray80012)), SizedBox(height: 1.v), Container(padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 5.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 33.v, width: 35.h, margin: EdgeInsets.only(bottom: 1.v), decoration: BoxDecoration(color: appTheme.blueGray10001, borderRadius: BorderRadius.circular(5.h))), Padding(padding: EdgeInsets.only(left: 10.h, top: 5.v, bottom: 7.v), child: Text("No selected file", style: CustomTextStyles.bodyMediumBluegray200))])), SizedBox(height: 14.v), CustomImageView(imagePath: ImageConstant.imgImage11, height: 196.v, width: 305.h)])); } 
/// Section Widget
Widget _buildAfterMealPreviewSection(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 44.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("After meal preview", style: CustomTextStyles.bodySmallGray80012), SizedBox(height: 1.v), CustomTextFormField(controller: aftermealpreviewController, hintText: "No selected file", contentPadding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 12.v))])); } 
/// Navigates to the dailyContainer1Screen when the action is triggered.
onTapImgArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.dailyContainer1Screen); } 
/// Navigates to the dailyContainer1Screen when the action is triggered.
onTapSubmitForm(BuildContext context) { Navigator.pushNamed(context, AppRoutes.dailyContainer1Screen); } 
 }
