import '../store_checkout_screen/widgets/productcardlist1_item_widget.dart';import '../store_checkout_screen/widgets/widget_item_widget.dart';import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_subtitle_one.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';class StoreCheckoutScreen extends StatelessWidget {const StoreCheckoutScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 1.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Items", style: theme.textTheme.titleSmall)), SizedBox(height: 10.v), _buildProductCardList(context), SizedBox(height: 18.v), _buildPaymentMethod(context), SizedBox(height: 37.v), _buildMerchandiseSubtotal1(context), SizedBox(height: 8.v), _buildShippingFee(context, shippingFeeText: "Total", priceText: "₱ 1400.00"), SizedBox(height: 5.v)])), bottomNavigationBar: _buildPlaceOrder(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 56.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDownGray800, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "Checkout")); } 
/// Section Widget
Widget _buildProductCardList(BuildContext context) { return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 11.0.v), child: SizedBox(width: 345.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray300)));}, itemCount: 2, itemBuilder: (context, index) {return Productcardlist1ItemWidget();}); } 
/// Section Widget
Widget _buildPaymentMethod(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Payment Method", style: theme.textTheme.titleSmall), SizedBox(height: 8.v), Wrap(runSpacing: 16.v, spacing: 16.h, children: List<Widget>.generate(3, (index) => WidgetItemWidget()))]); } 
/// Section Widget
Widget _buildMerchandiseSubtotal1(BuildContext context) { return Column(children: [_buildShippingFee(context, shippingFeeText: "Merchandise Subtotal (2 Items)", priceText: "₱ 1200.00"), SizedBox(height: 10.v), _buildShippingFee(context, shippingFeeText: "Shipping Fee", priceText: "₱ 200.00")]); } 
/// Section Widget
Widget _buildPlaceOrder(BuildContext context) { return Container(margin: EdgeInsets.only(left: 40.h, right: 40.h, bottom: 31.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Total amount", style: theme.textTheme.labelLarge), Text("₱ 1400.00", style: CustomTextStyles.titleSmallPrimary)]), CustomOutlinedButton(width: 138.h, text: "Place Order", buttonStyle: CustomButtonStyles.outlinePrimaryTL19)])); } 
/// Common widget
Widget _buildShippingFee(BuildContext context, {required String shippingFeeText, required String priceText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(shippingFeeText, style: CustomTextStyles.bodySmallGray80012.copyWith(color: appTheme.gray800))), Text(priceText, style: CustomTextStyles.labelLargeSemiBold_1.copyWith(color: appTheme.gray800))]); } 
/// Navigates to the storeMycartScreen when the action is triggered.
onTapArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.storeMycartScreen); } 
 }
