import 'package:flutter/material.dart';import 'package:gaiadhiwise/core/app_export.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_leading_image.dart';import 'package:gaiadhiwise/widgets/app_bar/appbar_title.dart';import 'package:gaiadhiwise/widgets/app_bar/custom_app_bar.dart';import 'package:gaiadhiwise/widgets/custom_outlined_button.dart';import 'package:gaiadhiwise/presentation/profile_two_bottomsheet/profile_two_bottomsheet.dart';class ProfileScreen extends StatelessWidget {const ProfileScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(height: SizeUtils.height, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [_buildArrowDown(context), Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(top: 109.v), padding: EdgeInsets.symmetric(horizontal: 36.h, vertical: 32.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.customBorderTL22), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.img38554682032936, height: 96.adaptSize, width: 96.adaptSize, radius: BorderRadius.circular(48.h)), SizedBox(height: 14.v), Text("Satoru Goju", style: theme.textTheme.titleLarge), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildSeventyOne(context, genderText: "Age", maleText: "22")), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildSeventyOne(context, genderText: "Gender", maleText: "Male")), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildSeventyOne(context, genderText: "Height", maleText: "190cm")), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildSeventyOne(context, genderText: "Weight", maleText: "75kg")), SizedBox(height: 49.v), CustomOutlinedButton(text: "Update password", onPressed: () {onTapUpdatePassword(context);}), SizedBox(height: 20.v), CustomOutlinedButton(text: "Logout", buttonStyle: CustomButtonStyles.outlineRed, onPressed: () {onTapLogout(context);}), SizedBox(height: 20.v)])))])))); } 
/// Section Widget
Widget _buildArrowDown(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 50.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup1076), fit: BoxFit.cover)), child: CustomAppBar(height: 30.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowDown, margin: EdgeInsets.only(left: 24.h, top: 3.v, bottom: 2.v), onTap: () {onTapArrowDown(context);}), centerTitle: true, title: AppbarTitle(text: "Profile")))); } 
/// Common widget
Widget _buildSeventyOne(BuildContext context, {required String genderText, required String maleText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(genderText, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.gray800)), Text(maleText, style: CustomTextStyles.bodyMediumGray800.copyWith(color: appTheme.gray800))]); } 
/// Navigates to the dailyContainer1Screen when the action is triggered.
onTapArrowDown(BuildContext context) { Navigator.pushNamed(context, AppRoutes.dailyContainer1Screen); } 

/// Shows a modal bottom sheet with [ProfileTwoBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapUpdatePassword(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>ProfileTwoBottomsheet(),isScrollControlled: true); } 
/// Navigates to the loginScreen when the action is triggered.
onTapLogout(BuildContext context) { Navigator.pushNamed(context, AppRoutes.loginScreen); } 
 }
